version: '3.8'

services:
#PROMETHEUS For Collect The Data From Different Exporters
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /var/lib/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    restart: unless-stopped

#GRAFANA For Visualisation The Data From Difference Data Sources
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Uhfafyf!1
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped

#INFLUXDB For Save Collected Data From Telegraf
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /etc/influxdb:/etc/influxdb:ro
      - /var/lib/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
    networks:
      - monitoring
    restart: unless-stopped

#TELEGRAF For Collect Data By SNMP Proto
  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    volumes:
      - /etc/telegraf:/etc/telegraf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    external: true
